### ISSUE TITLE
Expander - Wrong output for variables that don't exist

### ISSUE THREAD

**Issue by marineks** [marineks/42_Minishell#8]
Example:
`bash-5.0$ echo $IDONTEXIST

`

Whereas ours returns:
`(null)`

I think the problem comes from our split_var function, line30 : 
`ft_lstadd_back_token(&tk_lst, ft_lstnew_token(NULL, VAR, DEFAULT));`
To be checked

**Comment by tmanolis** [comment]
Issue resolved, le move 666 IQ
